// 페르소나별 "핵심 느낌" + "이미지 키워드" 사전. 정본: docs/work/todo/moodboard/moodboard-persona-list.md
// 키를 persona.ts의 AESTHETIC_CORES/LIFE_THEMES 원소 타입으로 묶어, 문서가 지적한
// "사전 키에 별칭 접미사가 붙어 페르소나 이름과 정확히 일치하지 않는 9종" 문제(예:
// 문서상 "클린 걸 · 댓 걸")가 런타임 접두사 매칭 없이도 안전하도록 처리했다 —
// 아래 키는 별칭을 뗀 AESTHETIC_CORES/LIFE_THEMES 원문 그대로다.
//
// 코어 14종 = 각 20개 · 테마 6종 = 각 10개 (moodboard-creation.md §3 예산과 동일 —
// build-board-prompt.ts가 이 배열 길이를 예산으로 그대로 쓴다).

import type { AestheticCore, LifeTheme } from "@/lib/mood-test/persona";

export type PersonaKeywordEntry = {
  feeling: string; // 핵심 느낌 — 프롬프트 비율 표의 "핵심 느낌" 열
  keywords: readonly string[]; // 작은 오브제 → 의상·질감 → 큰 장면 순
};

export const PERSONA_KEYWORDS: Record<
  AestheticCore | LifeTheme,
  PersonaKeywordEntry
> = {
  // ── 미학 코어 14종 ──
  "클린 걸": {
    feeling: "자기관리, 맑음, 루틴, 정돈",
    keywords: [
      "matcha latte",
      "gold hoop earrings",
      "clean skincare",
      "glass water bottle",
      "fresh flowers",
      "green smoothie",
      "soft towel",
      "healthy breakfast bowl",
      "organized daily planner",
      "tidy vanity",
      "linen sheets",
      "white bedding",
      "white tank top",
      "neutral activewear",
      "dewy skin",
      "slick bun",
      "morning light",
      "sunlit bathroom",
      "minimal room",
      "pilates studio",
    ],
  },
  "올드 머니": {
    feeling: "조용한 부, 품격, 클래식",
    keywords: [
      "pearl earrings",
      "vintage watch",
      "gold signet ring",
      "understated jewelry",
      "classic perfume bottle",
      "silk scarf",
      "equestrian detail",
      "champagne satin",
      "beige cashmere",
      "cream knit sweater",
      "navy cardigan",
      "linen blazer",
      "tailored trousers",
      "leather loafers",
      "antique mirror",
      "marble table",
      "heritage library",
      "tennis club",
      "country club",
      "quiet luxury",
    ],
  },
  코케트: {
    feeling: "리본, 여림, 로맨틱, 소녀성",
    keywords: [
      "ribbons",
      "pink bow",
      "heart charm",
      "pearls",
      "silky hair ribbon",
      "lace",
      "powder compact",
      "rose perfume",
      "frilly socks",
      "delicate gloves",
      "romantic diary",
      "satin",
      "blush pink",
      "ballet flats",
      "mary jane shoes",
      "tulle skirt",
      "corset top",
      "vanity mirror",
      "ballet studio",
      "soft focus",
    ],
  },
  "Y2K 키치": {
    feeling: "장난기, 과장, 반짝임, 2000년대",
    keywords: [
      "star stickers",
      "stickers",
      "butterfly clips",
      "lip gloss tube",
      "glitter",
      "flip phone",
      "bedazzled phone",
      "digital camera",
      "pink headphones",
      "rhinestone sunglasses",
      "fuzzy bag",
      "metallic handbag",
      "bubble letters",
      "glossy lips",
      "hot pink",
      "chrome",
      "low-rise denim",
      "mini skirt",
      "platform sandals",
      "retro web graphics",
    ],
  },
  "인디 슬리즈": {
    feeling: "흐트러짐, 밤, 반항, 필름감",
    keywords: [
      "red lipstick stain",
      "tangled headphones",
      "cheap beer",
      "vintage camera",
      "band poster",
      "eyeliner",
      "smudged makeup",
      "worn boots",
      "black skinny jeans",
      "leather jacket",
      "messy hair",
      "mirror selfie",
      "flash photo",
      "grainy film",
      "neon bar sign",
      "dark bedroom",
      "night street",
      "party floor",
      "underground club",
      "cigarette smoke atmosphere",
    ],
  },
  "다크 아카데미아": {
    feeling: "지적, 어두움, 고전, 고독",
    keywords: [
      "candle",
      "fountain pen",
      "leather-bound journal",
      "annotated poetry",
      "black coffee",
      "vintage clock",
      "books",
      "brown tweed",
      "wool coat",
      "oxford shoes",
      "brown leather satchel",
      "typewriter",
      "dim lamp light",
      "dark wood",
      "rainy window",
      "antique desk",
      "dusty shelves",
      "classical statue",
      "old library",
      "gothic architecture",
    ],
  },
  "라이트 아카데미아": {
    feeling: "공부, 햇살, 따뜻한 지성",
    keywords: [
      "pressed flowers",
      "pencil notes",
      "latte cup",
      "notebook",
      "open book",
      "classic novel",
      "coffee",
      "cream cardigan",
      "soft blazer",
      "beige trousers",
      "ivory tote bag",
      "linen",
      "white curtains",
      "sunlit desk",
      "window seat",
      "golden light",
      "warm library",
      "museum hallway",
      "campus",
      "morning study session",
    ],
  },
  코티지코어: {
    feeling: "자연, 손맛, 목가적, 느린 삶",
    keywords: [
      "wildflowers",
      "fresh berries",
      "farm eggs",
      "ceramic mug",
      "homemade bread",
      "straw hat",
      "gingham cloth",
      "basket",
      "handmade quilt",
      "picnic blanket",
      "lace curtain",
      "soft dress",
      "wooden table",
      "sun-dried laundry",
      "herb garden",
      "garden path",
      "flower field",
      "meadow",
      "rustic kitchen",
      "cottage",
    ],
  },
  페어리코어: {
    feeling: "몽환, 요정, 투명함, 숲",
    keywords: [
      "tiny mushrooms",
      "silver charms",
      "crystal necklace",
      "soft butterflies",
      "flower crown",
      "soft lavender",
      "sparkling dust",
      "moss",
      "dewy grass",
      "fairy wings",
      "sheer fabric",
      "ethereal dress",
      "iridescent light",
      "pastel haze",
      "moonlit pond",
      "glittering stream",
      "misty garden",
      "hidden woodland",
      "glowing forest",
      "dreamy fog",
    ],
  },
  코스탈: {
    feeling: "바다, 린넨, 여유, 햇빛",
    keywords: [
      "shell tray",
      "driftwood",
      "glass vase",
      "straw hat",
      "woven beach bag",
      "seaside breakfast",
      "blue stripes",
      "linen shirt",
      "bare feet",
      "white curtains",
      "weathered wood",
      "sand texture",
      "neutral tones",
      "soft beige sofa",
      "ocean window",
      "sunlit ocean",
      "coastal home",
      "warm sunlight",
      "sea breeze",
      "salt air",
    ],
  },
  "소프트 그런지": {
    feeling: "부드러운 반항, 음악, 검정",
    keywords: [
      "silver rings",
      "black nail polish",
      "concert ticket",
      "vinyl records",
      "messy eyeliner",
      "black lace",
      "dark floral print",
      "band tee",
      "plaid skirt",
      "worn denim",
      "oversized hoodie",
      "distressed knit",
      "boots",
      "leather boots",
      "moody mirror selfie",
      "bedroom posters",
      "guitar",
      "red neon",
      "smoky room",
      "soft grunge",
    ],
  },
  "테크 노어": {
    feeling: "차갑고 미래적, AI, 고립",
    keywords: [
      "sleek headphones",
      "reflective sunglasses",
      "silver laptop",
      "dark interface",
      "AI dashboard",
      "digital grid",
      "chrome",
      "metal texture",
      "black leather",
      "monochrome outfit",
      "black trench coat",
      "blue screen glow",
      "cold lighting",
      "low light",
      "minimal workstation",
      "neon",
      "glass building",
      "urban night",
      "futuristic city",
      "cyber minimal",
    ],
  },
  "맥시멀 글램": {
    feeling: "과감함, 장식, 화려함",
    keywords: [
      "statement earrings",
      "red lipstick",
      "layered jewelry",
      "luxury perfume",
      "sparkling clutch",
      "oversized sunglasses",
      "feather trim",
      "animal print",
      "bold pattern",
      "jewel tones",
      "velvet",
      "silk robe",
      "leopard coat",
      "dramatic heels",
      "glossy makeup",
      "baroque frame",
      "gold mirror",
      "vintage vanity",
      "crystal chandelier",
      "editorial pose",
    ],
  },
  "네오 로맨틱": {
    feeling: "현대적 낭만, 감정, 도시의 시",
    keywords: [
      "roses",
      "rose petals",
      "velvet ribbon",
      "antique locket",
      "handwritten letter",
      "poetry book",
      "romantic perfume",
      "red wine",
      "silk",
      "black dress",
      "deep burgundy",
      "candlelit table",
      "soft shadow",
      "dramatic light",
      "misty window",
      "cinematic balcony",
      "rainy street",
      "old theater",
      "city night",
      "melancholy sunset",
    ],
  },
  // ── 인생 테마 6종 ──
  러키걸: {
    feeling: "확신, 행운, 자기암시",
    keywords: [
      "four-leaf clover",
      "gold pen",
      "lucky charm",
      "angel numbers",
      "sparkles",
      "manifestation note",
      "gratitude list",
      "journal",
      "affirmation",
      "sunlight",
    ],
  },
  "커리어 보스": {
    feeling: "일잘러, 야망, 도시적 자신감",
    keywords: [
      "espresso",
      "calendar planner",
      "structured handbag",
      "laptop",
      "blazer",
      "sharp tailoring",
      "confident desk setup",
      "glass office",
      "city view",
      "office glam",
    ],
  },
  "웰니스 러너": {
    feeling: "건강, 회복, 아침, 지속성",
    keywords: [
      "hydration bottle",
      "green smoothie",
      "fresh towel",
      "running shoes",
      "yoga mat",
      "sweat",
      "morning stretch",
      "clean street",
      "sunrise",
      "wellness",
    ],
  },
  트래블러: {
    feeling: "자유, 이동, 낯선 풍경",
    keywords: [
      "passport",
      "postcard",
      "map",
      "airport coffee",
      "film photo",
      "suitcase",
      "train window",
      "motel",
      "sunset highway",
      "road trip",
    ],
  },
  스피리추얼: {
    feeling: "운명, 우주, 신비, 내면",
    keywords: [
      "crystals",
      "celestial necklace",
      "tarot",
      "silver candle",
      "incense",
      "dream journal",
      "astrology chart",
      "zodiac",
      "moonlight",
      "cosmic sky",
    ],
  },
  "코지 홈바디": {
    feeling: "집, 안정, 귀여움, 온기",
    keywords: [
      "tea",
      "soft socks",
      "plush toy",
      "book stack",
      "homemade snack",
      "blanket",
      "pajamas",
      "lamp light",
      "cozy sofa",
      "warm bedroom",
    ],
  },
};
